dev: true
game:
    auto_ban: 12
    auto_confirm: true
    auto_pick: 103
log:
    age: 7
    backups: 7
    compress: true
    filepath: ./log
    level: debug
    size: 1024
show_version: true
web:
    addr: :9365
